carro/urls.py
from django.urls import path

from carro.views import (vista, 
                         add_to_cart, 
                         borrar_carro, 
                         update_to_quantity,
                         borrar_item_carro)

app_name = "carro"

urlpatterns = [
    
    path('', vista, name="vista"),
    path('actualizar_cantidad/',update_to_quantity, name="update_to_quantity"),
    path('delete/', borrar_carro, name="borrar_carro"),
    path('<slug:slug>/',add_to_cart, name="update_to_cart"),
    path('delete_item/<int:item_carroid>/', borrar_item_carro, name="borrar_item_carro"),
   
    
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from producto.views import all_products, buscar

urlpatterns = [
    path('', all_products, name="all_products"),
    path('s/', buscar, name="buscar"),
    path('producto/', include('producto.urls')),
    path('carro/', include('carro.urls')),
    path('checkout/', include('pedido.urls')),
    path('cuentas/', include('cuenta.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

pedido/urls.py
from django.urls import path

from pedido.views import checkout, pedidos

app_name = "checkout"

urlpatterns = [
    path('', checkout,name="checkout"), 
    path('pedidos/', pedidos, name="user_orders"),
]

producto/urls.py
from django.urls import path

from producto.views import all_products, single

app_name = "producto"

urlpatterns = [
    path('', all_products, name="all"),
    path('<slug:slug>/', single, name="single_producto"),
]

carro/models.py
from django.db import models
from django.urls import reverse

from producto.models import Producto, Variacion


class Carro(models.Model):
    #items = models.ManyToManyField(CartItem, blank=True)
    #productos = models.ManyToManyField(Producto, blank=True)
    total = models.DecimalField(max_digits=100, decimal_places=2, default=0.00)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    activo = models.BooleanField(default=True)

    def __str__(self):
        return f"Carro id: {self.id}"
    

class CarroItemManager(models.Manager):
    def orderByTimestamp(self):
        return super(CarroItemManager, self).order_by("timestamp")

class CarroItem(models.Model):
    carro = models.ForeignKey(Carro, on_delete=models.CASCADE, null=True, blank=True)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    variaciones = models.ManyToManyField(Variacion, blank=True)
    cantidad = models.IntegerField(default=1)
    linea_total = models.DecimalField(default=10.99, max_digits=100,decimal_places=2)
    #notas = models.TextField(null=True, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = CarroItemManager()

    def __str__(self):
        return self.producto.titulo     
    
    def get_borrar_item_url(self):
        return reverse("carro:borrar_item_carro", kwargs={"item_carroid":self.id})

producto/models.py
import os
import shutil
from django.conf import settings
from django.db.models import Q
from django.urls import reverse

from django.db import models

class CategoriaManager(models.Manager):
    def categoriasActivas(self):
        return super(CategoriaManager, self).filter(active=True)

class Categoria(models.Model):
    titulo = models.CharField(max_length=120)
    descripcion = models.TextField(null=True, blank=True)
    slug = models.SlugField(unique=True)
    presentada = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    objects = CategoriaManager()

    class Meta:
        unique_together = ["titulo", "slug"]
        ordering = ["titulo"]

    def __str__(self):
        return self.titulo

class ProductoQueryset(models.QuerySet):
    def productosActivosxcategoria(self, slug=None):
        if slug is None:
            return self.filter(active=True, categoria=2)
        categoria = Categoria.objects.get(slug=slug)
        return self.filter(active=True, categoria=categoria)  

    def productosCategoriaExcluyendo1(self, categoria, id):
        return self.filter(categoria=categoria, active=True).exclude(id=id)  
    
    def buscar(self, query=None):
        if query is None or query == "":
            return self.none()
        lookups = (Q(titulo__icontains=query) | Q(descripcion__icontains=query) | Q(color__icontains=query))
        return self.filter(lookups)
    
    def productoIgualesDiferentesColoresExcluyedo1(self, titulo, id):
        return self.filter(active=True, titulo__iexact=titulo).exclude(id=id)

class ProductoManager(models.Manager):
    def get_queryset(self):
        return ProductoQueryset(self.model, using=self._db)

    def filtrar(self, slug = None):
        return self.get_queryset().productosActivosxcategoria(slug=slug)

    def filtrar2(self, categoria, id):
        return self.get_queryset().productosCategoriaExcluyendo1(categoria, id)
    
    def filtrar3(self, titulo, id):
        return self.get_queryset().productoIgualesDiferentesColoresExcluyedo1(titulo, id)
    
    def buscar(self, query=None):
        return self.get_queryset().buscar(query=query)


class Producto(models.Model):
    titulo = models.CharField(max_length=120)
    descripcion = models.TextField(null=True, blank=True)
    categoria = models.ManyToManyField(Categoria, blank=True)
    precio = models.DecimalField(decimal_places=2, max_digits=100, default=29.99)
    #Este campo me da que nunca lo uso
    #precio_venta = models.DecimalField(decimal_places=2, max_digits=100,\   
    #                                                     null=True, blank=True)
    color = models.CharField(max_length=120, blank=True, null=True)
    slug = models.SlugField(unique=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    update_defaults = models.BooleanField(default=False)

    objects = ProductoManager()

    class Meta:
        unique_together = ['titulo', 'slug']
        ordering = ['titulo']

    def __str__(self):
        return self.slug
     
    def delete(self, *args, **kwargs):
        ruta_directorio = f"productos/imagenes/{self.titulo}"
        full_directorio = os.path.join(settings.MEDIA_ROOT, ruta_directorio)
        if os.path.exists(full_directorio):
            shutil.rmtree(full_directorio)

        super(Producto,self).delete(*args, **kwargs)
    
    def get_absolute_url(self):
        return reverse("producto:single_producto", kwargs={'slug':self.slug})
    
    def get_carro_producto_url(self):
        return reverse("carro:update_to_cart", kwargs={'slug':self.slug})
    


def comercio_directorio_fotos(intance, filename):
    ruta_foto_nombre = f"productos/imagenes/{intance.producto.titulo}/{filename}"
    full_path = os.path.join(settings.MEDIA_ROOT, ruta_foto_nombre)
    if os.path.exists(full_path):
        os.remove(full_path)
    return ruta_foto_nombre

class ProductoImagenManager(models.Manager):
    def fotoActivaMiniatura(self):
        return super(ProductoImagenManager, self).filter(active=True, miniatura=True).order_by('-presentada')
    
    def fotoActivaNoPresentada(self):
        #NO USADO
        return super(ProductoImagenManager, self).filter(active=True, presentada=False)

    def fotoActivaPresentada(self):
        return self.get_queryset().filter(active=True, presentada=True)
        #Esto de abajo es lo mismo
        #return super(ProductoImagenManager, self).filter(active=True, presentada=True)

class ProductoImagen(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to=comercio_directorio_fotos)
    presentada = models.BooleanField(default=False)
    miniatura = models.BooleanField(default=False)
    active = models.BooleanField(default=True)
    updated = models.DateTimeField(auto_now=True)

    objects = ProductoImagenManager()

    class Meta:
        verbose_name = "Producto Imagen"
        verbose_name_plural = "Productos Imagenes"

    def __str__(self):
        return self.producto.titulo
    
    def delete (self, *args, **kwargs):
        print(self.imagen.path)
        if os.path.isfile(self.imagen.path):
            os.remove(self.imagen.path)                                  
        super(ProductoImagen,self).delete(*args, **kwargs)


class VariacionManager(models.Manager):
    def all(self):
        return super(VariacionManager, self).filter(active=True)

    def sizes(self):
        return self.all().filter(variacion='size')
    
    #def colors(self):
    #    return super().filter(active=True, variacion= "color")

VAR_CATEGORIES = (
    ('size', 'size'),
    ('color', 'color'),
    ('package', 'package'),
)

class Variacion(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    variacion = models.CharField(max_length=120, choices=VAR_CATEGORIES, default='size') 
    #creo que sobra la imagen
    imagen = models.ForeignKey(ProductoImagen, on_delete=models.CASCADE, null=True, blank=True)
    titulo = models.CharField(max_length=120)
    precio = models.DecimalField(max_digits=100, decimal_places=2, null=True, blank=True)
    active = models.BooleanField(default=True)
    updated = models.DateTimeField(auto_now=True)

    objects = VariacionManager()

    class Meta:
        verbose_name = "Variación"
        verbose_name_plural = "Variaciones"

    def __str__(self):
        return self.titulo

carro/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse

from producto.models import Producto, Variacion
from carro.models import Carro, CarroItem

def vista(request):
    msj_articulos = ""
    carro_vacio = False
   
    the_id = request.session.get('carro_id')
    print(the_id)
    if the_id:
        carro = Carro.objects.get(id=the_id)
        
        if carro.carroitem_set.count() == 0:
            carro_vacio = True
        elif carro.carroitem_set.count() == 1:
            msj_articulos = f"{carro.carroitem_set.count()} artículo"
        elif carro.carroitem_set.all().count() > 1:
            msj_articulos = f"{carro.carroitem_set.count()} artículos"

        carro_items = carro.carroitem_set.orderByTimestamp

        context = {
            "carro": carro_items,
            "total":carro.total,
            "carro_vacio":carro_vacio,
            "msj_articulos":msj_articulos
        }
    elif the_id == None:
        context = {
            'carro_vacio': True
        }
    
    return render(request, "carros/vista.html", context)


def update_to_quantity(request):
    msj_articulos = ""
    nuevo_total = 0.00  

    slug = request.GET.get("slug")
    qty = request.GET.get("qty")
  
    the_id = request.session.get('carro_id')
    carro = Carro.objects.get(id=the_id)

    producto = get_object_or_404(Producto, slug=slug)
    cart_item = CarroItem.objects.get(carro=carro, producto=producto)

    cart_item.cantidad = qty
    cart_item.linea_total = float(cart_item.cantidad) * float(cart_item.producto.precio)
    cart_item.save()

    for item in carro.carroitem_set.all(): 
        linea_total = float(item.producto.precio) * item.cantidad
        nuevo_total += linea_total
    
    request.session['items_total'] = carro.carroitem_set.count()
    carro.total = nuevo_total
    carro.save()

    carro_items = carro.carroitem_set.orderByTimestamp

    if carro.carroitem_set.count() == 1:
        msj_articulos = f"{carro.carroitem_set.count()} artículo"
    elif carro.carroitem_set.all().count() > 1:
        msj_articulos = f"{carro.carroitem_set.count()} artículos"

    context = {
        "msj_articulos":msj_articulos,
        "carro":carro_items,
        "total": carro.total
    }
    return render(request, "componentes/vista_ajax_div.html", context)
    #return redirect("carro:vista")
    #return render(request, "carros/vista.html", context)


def add_to_cart(request, slug):
    request.session.set_expiry(12000)
    nuevo_total = 0.00
    #notas = {} 
    product_var = []

    url = request.GET.get('url')

    the_id = request.session.get('carro_id')
    print(the_id)
    if the_id == None:
        nuevo_carro = Carro()
        nuevo_carro.save()
        request.session['carro_id'] = nuevo_carro.id
        the_id = nuevo_carro.id
    
    carro = Carro.objects.get(id=the_id)
    producto = get_object_or_404(Producto, slug=slug)

    if request.method == "POST":
        qty = request.POST["qty"]
        #color = request.POST["color"]
        #size = request.POST["size"]
        for item in request.POST:
            key = item
            val = request.POST[key]
            print(key, val)
            try:
                v = Variacion.objects.get(producto=producto, variacion__iexact=key, titulo__iexact = val)
                product_var.append(v)
            except:
                pass
        print(product_var)

        #cart_item, created = CarroItem.objects.get_or_create(carro=carro, producto=producto)
        #if created:
        #    print("creado")
        cart_item = CarroItem.objects.create(carro=carro, producto=producto)

        #if int(qty) <= 0:
        #    cart_item.delete()
        #else:
        if len(product_var) > 0:
            #antes de grabar las nuevas variaciones, hay que borrar las que hubiera
            #cart_item.variaciones.clear()
            #for item in product_var:
            cart_item.variaciones.add(*product_var)
        
        cart_item.cantidad = qty
        #cart_item.notas = notas
        cart_item.linea_total = float(cart_item.cantidad) * float(cart_item.producto.precio)
        cart_item.save()
        """
        if not cart_item in carro.items.all():
            carro.items.add(cart_item)
        else:
            carro.items.remove(cart_item)
        """

        for item in carro.carroitem_set.all():
            linea_total = float(item.producto.precio) * item.cantidad
            nuevo_total += linea_total
        
        request.session['items_total'] = carro.carroitem_set.count()
        carro.total = nuevo_total
        carro.save()
        
        #return redirect("carro:vista")
        #return redirect('producto:all')
        return redirect(url)
    else:
        return redirect(url)


def borrar_item_carro(request, item_carroid):
    nuevo_total = 0.00

    url = request.GET.get("url")
    the_id = request.session.get('carro_id') 

    #cojo carro_item en base a id que viene por parametro y lo pongo a None
    cart_item = CarroItem.objects.get(id=item_carroid)
    cart_item.carro = None
    cart_item.save()

    #Cojo carro contabilizo su total
    carro = Carro.objects.get(id=the_id)
    for item in carro.carroitem_set.all(): 
        linea_total = float(item.producto.precio) * item.cantidad
        nuevo_total += linea_total

    #Actualizo total items en en session y grabo total de carro
    request.session['items_total'] = carro.carroitem_set.count()
    carro.total = nuevo_total
    carro.save()

    if url:
        return redirect(url)
    return redirect("carro:vista")
  
    
    
def borrar_carro(request):
    the_id = request.session.get('carro_id')
    carro = Carro.objects.get(id=the_id)
    """
    for producto in carro.productos.all():
        carro.productos.remove(producto)
    """
    carro.carroitem_set.clear()
    carro.total = 0
    carro.save()
    request.session["items_total"] = 0
    return redirect("carro:vista")

templates/carros/vista.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Carro{% endblock title %}

{% block content %}
    <style>
        .a_resaltado{
            text-decoration: none;
            color: black;
        }
    </style>
    
    {% if carro_vacio %}
        <div class="card mb-3" style="margin: 10px; height:250px">
            
            <div class="card-body" style="margin:120px">
                <h1 style="text-align: center;" class="card-title">Llena tu cesta de nuevas tendencias.</h1>
                
                <p class="card-text" style="text-align: center;">
                    <button type="button" class="btn btn-outline-primary">Iniciar Sesion</button>&nbsp;&nbsp;&nbsp;
                    <a href="{% url 'producto:all' %}" type="button" class="btn btn-primary">Volver a la tienda</a>

                </p>
            </div>
        </div>

    {% else %}
    
        <div id="pintar_cesta">
        <div class="row" style="margin: 10px;">
            
            <div class="col-8">
                
                <div class="card mb-3" style="max-width: 840px;">
                    <div class="row g-0">
                        <h1 style="margin: 10px;">Tu cesta ({{msj_articulos}})</h1>
                        <a style="margin: 10px; text-decoration:none; color:black" href="{% url 'carro:borrar_carro' %}"><u>Borrar Carro</u></a>
                        {% for item in carro %}
                            <div class="col-md-2">
                                {% if item.producto.productoimagen_set.fotoActivaPresentada %}
                                    {% for imagen in item.producto.productoimagen_set.fotoActivaPresentada %}
                                        <img src="{{imagen.imagen.url}}" class="img-thumbnail" alt="{{item.titulo}}" 
                                                    width="200px" height="400px" style="margin: 10px;">
                                    {% endfor %}
                                {% else %}
                                    <img src="{% static 'img/placeholder.png' %}" class="img-fluid rounded-start" alt=""  
                                                    width="200px" height="400px" style="margin: 10px;">
                                {% endif %}
                            </div>
                            
                            <div class="col-md-10">
                                <div class="card-body">
                                    <table class="table table-borderless table-sm">
                                        <tbody>
                                            <tr>
                                                <td>
                                                    <b>{{item.producto.titulo|title}}</b>
                                                    <br>
                                                    {{item.producto.descripcion|truncatewords:8}}
                                                    <br>
                                                    Color: {{item.producto.color}}
                                                    <br>
                                                    Talla: 
                                                    {% for talla in item.variaciones.all %}
                                                        {{talla}}
                                                    {% endfor %}

                                                </td>
                                                <td></td>
                                                <td>
                                                    <select onchange="pasar_cantidad('{{item.producto.slug}}', this)" class="form-select form-select-sm" aria-label="Small select example">
                                                        {% if item.cantidad == 1 %}
                                                            <option value="{{item.cantidad}}" selected>
                                                                {{item.cantidad}}
                                                            </option>
                                                        {% else %}
                                                            <option value="1">1</option>
                                                        {% endif %}
                                                        {% if item.cantidad == 2 %}
                                                            <option value="{{item.cantidad}}" selected>
                                                                {{item.cantidad}}
                                                            </option>
                                                        {% else %}
                                                            <option value="2">2</option>
                                                        {% endif %}
                                                        {% if item.cantidad == 3 %}
                                                            <option value="{{item.cantidad}}" selected>
                                                                {{item.cantidad}}
                                                            </option>
                                                        {% else %}
                                                            <option value="3">3</option>
                                                        {% endif %}
                                                        {% if item.cantidad == 4 %}
                                                            <option value="{{item.cantidad}}" selected>
                                                                {{item.cantidad}}
                                                            </option>
                                                        {% else %}
                                                            <option value="4">4</option>
                                                        {% endif %}
                                                        {% if item.cantidad == 5 %}
                                                            <option value="{{item.cantidad}}" selected>
                                                                {{item.cantidad}}
                                                            </option>
                                                        {% else %}
                                                            <option value="5">5</option>
                                                        {% endif %}
                                                        {% if item.cantidad == 6 %}
                                                            <option value="{{item.cantidad}}" selected>
                                                                {{item.cantidad}}
                                                            </option>
                                                        {% else %}
                                                            <option value="6">6</option>
                                                        {% endif %}
 
                                                    </select>
                                                </td>
                                                <td>{{item.cantidad}}</td>
                                            </tr>
                                            <tr>
                                                <td>Entrega rápida:</td>
                                                <td></td>
                                                <td></td>
                                            </tr>
                                            <tr> 
                                                <td>
                                                    <a href="{{item.get_borrar_item_url}}" class="a_resaltado">
                                                        <img src="{% static 'img/icon-delete.png' %}" width="25px">
                                                            Eliminar {{item.id}}
                                                    </a>
                                                </td>
                                                <td>Mover a favoritos</td>
                                                <td><b>{{item.linea_total}}</b></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                    
                                </div>
                            </div>
                            <hr/>
                        {% endfor %}
                        
                    </div>
                </div>
                
            </div>
            
            <div class="col-4">
                <div class="card mb-3" style="max-width: 540px;">
                    <h1 style="margin: 10px;">Total</h1>
                    <table class="table table-borderless" style="margin: 10px;">
                        
                        <tbody>
                            <tr>
                                <td>Subtotal</td>
                                <th scope="col"></th>
                                <th scope="col"></th>
                                <td scope="col">{{total}} €</td>
                            </tr>
                        </tbody>
                        <tbody>
                            <tr>
                                <td>Envío</td>
                                <th scope="col"></th>
                                <th scope="col"></th>
                                <td scope="col">0,00 €</td>
                                
                            </tr>
                        
                        </tbody>

                        <tbody> 
                            <tr>
                                <th scope="col">Total (IVA incluido)</th>
                                <th scope="col"></th>
                                <th scope="col"></th>
                                <th scope="col">{{total}} €</th>

                            </tr>

                        </tbody>
                        <tbody>
                            <tr>
                                <td colspan="4">
                                    <div class="d-grid gap-2 col-11 mx-auto">

                                        <a href="{% url 'checkout:checkout' %}" type="button" class="btn btn-primary btn-lg">Comenzar pedido</a>
                                    </div>
                                </td>
                            </tr>
                        </tbody>

                    </table>

                    
                </div>
            </div>

        </div>
        </div>
    {% endif %}

{% endblock content %}


{% block javascript/jquery %}
    <script>
        function pasar_cantidad(slug, cantidad){
            console.log(cantidad.value);
            console.log(slug);
            $.ajax({
                type: 'GET',
                url: "{% url 'carro:update_to_quantity' %}",
                data: {"slug":slug,"qty":cantidad.value},
                success: function(msg){
                    console.log("esta de vuelta");
                    $("#pintar_cesta").html(msg)
                }
            });
        }
    </script>
{% endblock javascript/jquery %}