carro/urls.py
from django.urls import path

from carro.views import (vista, 
                         add_to_cart, 
                         borrar_carro, 
                         update_to_quantity,
                         borrar_item_carro)

app_name = "carro"

urlpatterns = [
    
    path('', vista, name="vista"),
    path('actualizar_cantidad/',update_to_quantity, name="update_to_quantity"),
    path('delete/', borrar_carro, name="borrar_carro"),
    path('<slug:slug>/',add_to_cart, name="update_to_cart"),
    path('delete_item/<int:item_carroid>/', borrar_item_carro, name="borrar_item_carro"),
   
    
]

cuenta/urls.py
from django.urls import path

from cuenta.views import (logout_view, 
                          login_view, 
                          register_view,
                          register_partial_view,
                          login_partial_view)

app_name = "cuentas"

urlpatterns = [
    path('logout/',logout_view, name="auth_logout"),
    path('login/', login_view, name="auth_login"),
    path('register/', register_view, name="auth_register"),
    #parciales de login y register
    path('login/partial/', login_partial_view, name="auth_login_partial"),
    path('register/partial/', register_partial_view, name="auth_register_partial"),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from producto.views import all_products, buscar

urlpatterns = [
    path('', all_products, name="all_products"),
    path('s/', buscar, name="buscar"),
    path('producto/', include('producto.urls')),
    path('carro/', include('carro.urls')),
    path('checkout/', include('pedido.urls')),
    path('cuentas/', include('cuenta.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

pedido/urls.py
from django.urls import path

from pedido.views import checkout, pedidos

app_name = "checkout"

urlpatterns = [
    path('', checkout,name="checkout"), 
    path('pedidos/', pedidos, name="user_orders"),
]

producto/urls.py
from django.urls import path

from producto.views import all_products, single

app_name = "producto"

urlpatterns = [
    path('', all_products, name="all"),
    path('<slug:slug>/', single, name="single_producto"),
]

producto/models.py
import os
import shutil
from django.conf import settings
from django.db.models import Q
from django.urls import reverse

from django.db import models

class CategoriaManager(models.Manager):
    def categoriasActivas(self):
        return super(CategoriaManager, self).filter(active=True)

class Categoria(models.Model):
    titulo = models.CharField(max_length=120)
    descripcion = models.TextField(null=True, blank=True)
    slug = models.SlugField(unique=True)
    presentada = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    objects = CategoriaManager()

    class Meta:
        unique_together = ["titulo", "slug"]
        ordering = ["titulo"]

    def __str__(self):
        return self.titulo

class ProductoQueryset(models.QuerySet):
    def productosActivosxcategoria(self, slug=None):
        if slug is None:
            return self.filter(active=True, categoria=2)
        categoria = Categoria.objects.get(slug=slug)
        return self.filter(active=True, categoria=categoria)  

    def productosCategoriaExcluyendo1(self, categoria, id):
        return self.filter(categoria=categoria, active=True).exclude(id=id)  
    
    def buscar(self, query=None):
        if query is None or query == "":
            return self.none()
        lookups = (Q(titulo__icontains=query) | Q(descripcion__icontains=query) | Q(color__icontains=query))
        return self.filter(lookups)
    
    def productoIgualesDiferentesColoresExcluyedo1(self, titulo, id):
        return self.filter(active=True, titulo__iexact=titulo).exclude(id=id)

class ProductoManager(models.Manager):
    def get_queryset(self):
        return ProductoQueryset(self.model, using=self._db)

    def filtrar(self, slug = None):
        return self.get_queryset().productosActivosxcategoria(slug=slug)

    def filtrar2(self, categoria, id):
        return self.get_queryset().productosCategoriaExcluyendo1(categoria, id)
    
    def filtrar3(self, titulo, id):
        return self.get_queryset().productoIgualesDiferentesColoresExcluyedo1(titulo, id)
    
    def buscar(self, query=None):
        return self.get_queryset().buscar(query=query)


class Producto(models.Model):
    titulo = models.CharField(max_length=120)
    descripcion = models.TextField(null=True, blank=True)
    categoria = models.ManyToManyField(Categoria, blank=True)
    precio = models.DecimalField(decimal_places=2, max_digits=100, default=29.99)
    #Este campo me da que nunca lo uso
    #precio_venta = models.DecimalField(decimal_places=2, max_digits=100,\   
    #                                                     null=True, blank=True)
    color = models.CharField(max_length=120, blank=True, null=True)
    slug = models.SlugField(unique=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    update_defaults = models.BooleanField(default=False)

    objects = ProductoManager()

    class Meta:
        unique_together = ['titulo', 'slug']
        ordering = ['titulo']

    def __str__(self):
        return self.slug
     
    def delete(self, *args, **kwargs):
        ruta_directorio = f"productos/imagenes/{self.titulo}"
        full_directorio = os.path.join(settings.MEDIA_ROOT, ruta_directorio)
        if os.path.exists(full_directorio):
            shutil.rmtree(full_directorio)

        super(Producto,self).delete(*args, **kwargs)
    
    def get_absolute_url(self):
        return reverse("producto:single_producto", kwargs={'slug':self.slug})
    
    def get_carro_producto_url(self):
        return reverse("carro:update_to_cart", kwargs={'slug':self.slug})
    


def comercio_directorio_fotos(intance, filename):
    ruta_foto_nombre = f"productos/imagenes/{intance.producto.titulo}/{filename}"
    full_path = os.path.join(settings.MEDIA_ROOT, ruta_foto_nombre)
    if os.path.exists(full_path):
        os.remove(full_path)
    return ruta_foto_nombre

class ProductoImagenManager(models.Manager):
    def fotoActivaMiniatura(self):
        return super(ProductoImagenManager, self).filter(active=True, miniatura=True).order_by('-presentada')
    
    def fotoActivaNoPresentada(self):
        #NO USADO
        return super(ProductoImagenManager, self).filter(active=True, presentada=False)

    def fotoActivaPresentada(self):
        return self.get_queryset().filter(active=True, presentada=True)
        #Esto de abajo es lo mismo
        #return super(ProductoImagenManager, self).filter(active=True, presentada=True)

class ProductoImagen(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to=comercio_directorio_fotos)
    presentada = models.BooleanField(default=False)
    miniatura = models.BooleanField(default=False)
    active = models.BooleanField(default=True)
    updated = models.DateTimeField(auto_now=True)

    objects = ProductoImagenManager()

    class Meta:
        verbose_name = "Producto Imagen"
        verbose_name_plural = "Productos Imagenes"

    def __str__(self):
        return self.producto.titulo
    
    def delete (self, *args, **kwargs):
        print(self.imagen.path)
        if os.path.isfile(self.imagen.path):
            os.remove(self.imagen.path)                                  
        super(ProductoImagen,self).delete(*args, **kwargs)


class VariacionManager(models.Manager):
    def all(self):
        return super(VariacionManager, self).filter(active=True)

    def sizes(self):
        return self.all().filter(variacion='size')
    
    #def colors(self):
    #    return super().filter(active=True, variacion= "color")

VAR_CATEGORIES = (
    ('size', 'size'),
    ('color', 'color'),
    ('package', 'package'),
)

class Variacion(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    variacion = models.CharField(max_length=120, choices=VAR_CATEGORIES, default='size') 
    #creo que sobra la imagen
    imagen = models.ForeignKey(ProductoImagen, on_delete=models.CASCADE, null=True, blank=True)
    titulo = models.CharField(max_length=120)
    precio = models.DecimalField(max_digits=100, decimal_places=2, null=True, blank=True)
    active = models.BooleanField(default=True)
    updated = models.DateTimeField(auto_now=True)

    objects = VariacionManager()

    class Meta:
        verbose_name = "Variación"
        verbose_name_plural = "Variaciones"

    def __str__(self):
        return self.titulo

templates/componentes/cesta_canvas.html
{% load static %}

<div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasRight" aria-labelledby="offcanvasRightLabel" style="color: black;">
    <div class="offcanvas-header">
      <h1 class="offcanvas-title" id="offcanvasRightLabel">Cesta</h5>
      <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    
    {% if previo_carro_vacio %}
        <div class="card mb-3">
            <div class="card-body">
                <h4 style="text-align: center;" class="card-title">Tu Cesta</h4>
                <p style="text-align: center;" class="card-title">Llena tu cesta de nuevas tendencias.</p>
                <p class="card-text" style="text-align: center;">
                    <h4 style="text-align: center;" class="card-title"><b>¿Necesitas inspiración?</b></h4>
                    <a href="{% url 'producto:all' %}" type="button" class="btn btn-primary">Ver novedades</a>
                </p>
            </div>
        </div>
    {% else %}
        <div class="row"> 
            <div class="col-12">  
                <div class="card" >
                    <div class="row g-0">
                        
                        {% for item in previo_carro %}
                            <div class="col-md-2">
                                {% if item.producto.productoimagen_set.fotoActivaPresentada %}
                                    {% for imagen in item.producto.productoimagen_set.fotoActivaPresentada %}
                                        <img src="{{imagen.imagen.url}}" class="img-thumbnail" alt="{{item.titulo}}" 
                                                    width="200px" height="400px" style="margin: 10px;">
                                    {% endfor %}
                                {% else %}
                                    <img src="{% static 'img/placeholder.png' %}" class="img-fluid rounded-start" alt=""  
                                                    width="200px" height="400px" style="margin: 10px;">
                                {% endif %}
                            </div>
                            
                            <div class="col-md-10">
                                <div class="card-body">

                                    <b>{{item.producto.titulo|title}}</b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b>{{item.linea_total}} €</b>                    
                                    <br>
                                    {{item.producto.descripcion|truncatewords:2}}
                                    <br>
                                    Talla: 
                                        {% for talla in item.variaciones.all %}
                                            {{talla}}
                                        {% endfor %}
                                    <br>
                                    Cantidad: 1
                                    <br>
                                    <small>
                                        <a href="{{item.get_borrar_item_url}}?url={{request.get_full_path}}&qty=0" class="a_resaltado">
                                        
                                            Eliminar
                                        </a>       
                                            | Mover a favoritos
                                    </small>
    
                                </div>
                            </div>
                            <hr/>
                        {% endfor %}
                        <div style="margin: 10px;">
                            <table class="table table-borderless">
                                
                                <tr>
                                    <td>Envío</td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td>0,00 €</td>
                                </tr>
                                <tr>
                                    <td><b>Total</b> (IVA incluido)</td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td><b style="font-size: 25px;">{{previo_total}} €</b></td>
                                </tr>
                                
                            </table>
                            
            
                            <div class="d-grid gap-2 col-11 mx-auto">

                                <a href="{% url 'carro:vista' %}" type="button" class="btn btn-primary btn-lg">Comenzar pedido</a>
                            </div>
                        </div>

                    </div>
                </div>
                
            </div>
        </div>
    {% endif%}

</div>

templates/componentes/footer.html
<div class="container">
<footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
  <p class="col-md-4 mb-0 text-body-secondary">&copy; 2023 Company, Inc</p>

  <a href="/" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
    <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
  </a>

  <ul class="nav col-md-4 justify-content-end">
    <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Home</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Features</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Pricing</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">FAQs</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">About</a></li>
  </ul>
</footer>
</div>

<div class="b-example-divider"></div>

templates/componentes/navbar.html
{% load static %}
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
  <symbol id="bootstrap" viewBox="0 0 118 94">
    <title>Bootstrap</title>
    <path fill-rule="evenodd" clip-rule="evenodd"
      d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z">
    </path>
  </symbol>
  <symbol id="home" viewBox="0 0 16 16">
    <path
      d="M8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4.5a.5.5 0 0 0 .5-.5v-4h2v4a.5.5 0 0 0 .5.5H14a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146zM2.5 14V7.707l5.5-5.5 5.5 5.5V14H10v-4a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5v4H2.5z" />
  </symbol>
  <symbol id="speedometer2" viewBox="0 0 16 16">
    <path
      d="M8 4a.5.5 0 0 1 .5.5V6a.5.5 0 0 1-1 0V4.5A.5.5 0 0 1 8 4zM3.732 5.732a.5.5 0 0 1 .707 0l.915.914a.5.5 0 1 1-.708.708l-.914-.915a.5.5 0 0 1 0-.707zM2 10a.5.5 0 0 1 .5-.5h1.586a.5.5 0 0 1 0 1H2.5A.5.5 0 0 1 2 10zm9.5 0a.5.5 0 0 1 .5-.5h1.5a.5.5 0 0 1 0 1H12a.5.5 0 0 1-.5-.5zm.754-4.246a.389.389 0 0 0-.527-.02L7.547 9.31a.91.91 0 1 0 1.302 1.258l3.434-4.297a.389.389 0 0 0-.029-.518z" />
    <path fill-rule="evenodd"
      d="M0 10a8 8 0 1 1 15.547 2.661c-.442 1.253-1.845 1.602-2.932 1.25C11.309 13.488 9.475 13 8 13c-1.474 0-3.31.488-4.615.911-1.087.352-2.49.003-2.932-1.25A7.988 7.988 0 0 1 0 10zm8-7a7 7 0 0 0-6.603 9.329c.203.575.923.876 1.68.63C4.397 12.533 6.358 12 8 12s3.604.532 4.923.96c.757.245 1.477-.056 1.68-.631A7 7 0 0 0 8 3z" />
  </symbol>
  <symbol id="table" viewBox="0 0 16 16">
    <path
      d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2zm15 2h-4v3h4V4zm0 4h-4v3h4V8zm0 4h-4v3h3a1 1 0 0 0 1-1v-2zm-5 3v-3H6v3h4zm-5 0v-3H1v2a1 1 0 0 0 1 1h3zm-4-4h4V8H1v3zm0-4h4V4H1v3zm5-3v3h4V4H6zm4 4H6v3h4V8z" />
  </symbol>
  <symbol id="people-circle" viewBox="0 0 16 16">
    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z" />
    <path fill-rule="evenodd"
      d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z" />
  </symbol>
  <symbol id="grid" viewBox="0 0 16 16">
    <path
      d="M1 2.5A1.5 1.5 0 0 1 2.5 1h3A1.5 1.5 0 0 1 7 2.5v3A1.5 1.5 0 0 1 5.5 7h-3A1.5 1.5 0 0 1 1 5.5v-3zM2.5 2a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 1h3A1.5 1.5 0 0 1 15 2.5v3A1.5 1.5 0 0 1 13.5 7h-3A1.5 1.5 0 0 1 9 5.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zM1 10.5A1.5 1.5 0 0 1 2.5 9h3A1.5 1.5 0 0 1 7 10.5v3A1.5 1.5 0 0 1 5.5 15h-3A1.5 1.5 0 0 1 1 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 9h3a1.5 1.5 0 0 1 1.5 1.5v3a1.5 1.5 0 0 1-1.5 1.5h-3A1.5 1.5 0 0 1 9 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3z" />
  </symbol>
</svg>
<style>
  #abrir_canvas:hover > div{
    display: block;
  }
</style>

<header class="p-3 text-bg-dark">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">

        <div class="">
          <img src="{% static 'img/cr_avatar.png' %}" width='60px' height='52px' class="rounded">
        </div>
      </a>

      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li><a href="{% url 'producto:all' %}" class="nav-link px-2 text-secondary">Costura Real</a></li>
        <li><a href="#" class="nav-link px-2 text-white">Features</a></li>
        <li><a href="#" class="nav-link px-2 text-white">Pricing</a></li>
        <li><a href="#" class="nav-link px-2 text-white">FAQs</a></li>

        <li><a href="#" class="nav-link px-2 text-white">About</a></li>

        <form class="d-flex" role="search" action="{% url 'buscar' %}" method="get">

          <li style="margin-left: 30px;">
            <input name="q" type="search" class="form-control form-control-dark text-bg-dark" placeholder="Buscar..."
              aria-label="Search">
          </li>

          <li style="margin-left: 10px;">
            <button type="submit" class="btn btn-outline-light me-2">Buscar</button>
          </li>
        </form>

      </ul>

      <div class="text-end">
        <button type="button" class="btn btn-outline-light me-2">Login</button>
        <button type="button" class="btn btn-warning">Sign-up</button>

      </div>
      {% if request.user.is_authenticated %}
        <!--Drop down de usuario LOGADO-->
        <ul class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"
            style="color: white">
            <img src="{% static 'img/usuario.png' %}" style="width: 50px;">
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Tu perfil</a></li>
            <li><a class="dropdown-item" href="#">Pedidos</a></li>
            <li><a class="dropdown-item" href="#">Devolver artículo</a></li>
            <li><a class="dropdown-item" href="#">Tus tallas</a></li>
            <li><a class="dropdown-item" href="#">Ayuda y Contacto</a></li>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'cuentas:auth_logout'%}" style="color: blueviolet;">
                ¿No eres {{request.user}}, Desconectar?
              </a>
            </li>
          </ul>
        </ul>
      {% else %}
        <!--Drop down de usuario DESLOGADO-->
        <ul class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"
            style="color: white">
            <img src="{% static 'img/usuario.png' %}" style="width: 50px; ">
          </a>
          <ul class="dropdown-menu">
            <div class="d-grid gap-2">
              <button type="button" class="btn btn-dark" style="margin:10px">Inicio Sesión</button>
            </div>
            <li>
              <a class="dropdown-item" href="#">
                <span style="color: blueviolet;">¿Nuevo cliente?</span> 
                Regístrate ahora
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li><a class="dropdown-item" href="#">Tu perfil</a></li>
            <li><a class="dropdown-item" href="#">Pedidos</a></li>
            <li><a class="dropdown-item" href="#">Devolver artículo</a></li>
            <li><a class="dropdown-item" href="#">Ayuda y Contacto</a></li>

          </ul>
        </ul>
      {% endif %}
      <ul style="text-align: center;" >
        {% if not request.session.items_total or request.get_full_path == "/carro/" %}
          {% if not request.session.items_total %}
            <a href="{% url 'carro:vista' %}">
                
              <img src="{% static 'img/carro_azul.png' %}" style="width: 50px;">
              <span class="badge text-bg-warning"> 
                  0
              </span>
            </a>
          {% else %}
          
            <img src="{% static 'img/carro_azul.png' %}" style="width: 50px;">
            <span class="badge text-bg-warning"> 
                {{request.session.items_total}}
            </span>
            
          {% endif %}
        {% elif request.session.items_total %}
        
          <a href="" data-bs-toggle="offcanvas" aria-controls="offcanvasRight" data-bs-target="#offcanvasRight" id="abrir_canvas">
            
            <img src="{% static 'img/carro_azul.png' %}" style="width: 50px;">
            <span class="badge text-bg-warning">
                {{request.session.items_total}}
            </span>
          </a>
        {% endif %}
        
      </ul>
    </div>
  </div>

  <!--CANVAS-->
  {% include 'componentes/cesta_canvas.html' %}

</header>

{% block javascript/jquery %}
  <script>

  </script>
{% endblock javascript/jquery %}


<div class="b-example-divider"></div>

templates/componentes/paginador.html
<nav aria-label="..." style="margin-top: 10px;">
    <ul class="pagination justify-content-center">
        {% if productos.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?{{path_categoria}}&page=1" style="color:black;">Primera</a>
            </li>

            <li class="page-item">
                <a class="page-link" href="?{{path_categoria}}&page={{productos.previous_page_number}}">Previous</a>
            </li>
        {% endif %}
        
        {% for pagina in paginas %}
            <li class="page-item{% if pagina_actual == pagina %} active {% endif %}" aria-current="page">
                <a class="page-link" href="?{{path_categoria}}&page={{pagina}}">{{pagina}}</a>
            </li>
        {% endfor %}
        
        {% if productos.has_next %}
            <li class="page-item">
                <a class="page-link" href="?{{path_categoria}}&page={{productos.next_page_number}}">Next</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?{{path_categoria}}&page={{productos.paginator.num_pages}}">Última</a>
            </li>
        {% endif %}
    </ul>
</nav>

templates/componentes/sidebar.html
<main class="d-flex flex-nowrap" style="margin-top: 10px;">
    
    <div class="d-flex flex-column flex-shrink-0 p-3 text-bg-dark" style="width: 280px;">
        <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
            
            <span class="fs-4">Categoría</span>
        </a>
        <hr>
        <ul class="nav nav-pills flex-column mb-auto">
            
            {% for categoria in categorias %}
                
                <li class="nav-item" id="li_resaltado_sidebar">
                    <a href="{% url 'producto:all'%}?categoria={{categoria.slug}}" class="nav-link" aria-current="page" style="color: aliceblue;">
                        {{categoria.titulo|title}}
                    </a>
                </li>

            {% endfor %}
        
        </ul>
        <hr>

    </div>

</main>