carro/urls.py
from django.urls import path

from carro.views import (vista, 
                         add_to_cart, 
                         borrar_carro, 
                         update_to_quantity,
                         borrar_item_carro)

app_name = "carro"

urlpatterns = [
    
    path('', vista, name="vista"),
    path('actualizar_cantidad/',update_to_quantity, name="update_to_quantity"),
    path('delete/', borrar_carro, name="borrar_carro"),
    path('<slug:slug>/',add_to_cart, name="update_to_cart"),
    path('delete_item/<int:item_carroid>/', borrar_item_carro, name="borrar_item_carro"),
   
    
]

cuenta/urls.py
from django.urls import path

from cuenta.views import (logout_view, 
                          login_view, 
                          register_view,
                          register_partial_view,
                          login_partial_view)

app_name = "cuentas"

urlpatterns = [
    path('logout/',logout_view, name="auth_logout"),
    path('login/', login_view, name="auth_login"),
    path('register/', register_view, name="auth_register"),
    #parciales de login y register
    path('login/partial/', login_partial_view, name="auth_login_partial"),
    path('register/partial/', register_partial_view, name="auth_register_partial"),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from producto.views import all_products, buscar

urlpatterns = [
    path('', all_products, name="all_products"),
    path('s/', buscar, name="buscar"),
    path('producto/', include('producto.urls')),
    path('carro/', include('carro.urls')),
    path('checkout/', include('pedido.urls')),
    path('cuentas/', include('cuenta.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

cuenta/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser

from django.db import models

User = settings.AUTH_USER_MODEL

"""
class CustomUser(AbstractUser):
    email = models.EmailField(max_length=100, unique=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = [] #estos campos son requeridos a la hora de crear un usuario por consola
"""




class UsuarioStripe(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.SET_NULL, blank=True, null=True)
    stripe_id = models.CharField(max_length=120)
    fecha_nacimiento = models.DateField(max_length=10, null=True, blank=True)

    class Meta:
        verbose_name_plural = "Usuarios de Stripe"

    def __str__(self):
        return self.usuario.username
    

cuenta/forms.py
from django.core import validators
from django import forms

from django.contrib.auth.models import User

class RegistrationForm(forms.ModelForm):
    
    class Meta:
        model = User
        fields = ["username","first_name", "last_name", "email"]

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Las contraseñas no coinciden")
        return password2
    
    #sobre escribir el metodo save
    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.set_password(self.cleaned_data.get('password1'))
        if commit:
            user.save()
        return user
    
    username = forms.CharField(label="Usuario*",
                               required=True,
                               widget=forms.TextInput(
                                   attrs={"placeholder":"Usuario",
                                          'class':'form-control'}
                               ))
    first_name = forms.CharField(label="Nombre*", 
                                 required=True,
                                 widget=forms.TextInput(
                                     attrs={"placeholder":"Nombre",
                                            'class':'form-control'}
                                 ))
    last_name = forms.CharField(label="Apellidos*",
                                required=True,
                                widget=forms.TextInput(
                                    attrs={"placeholder":"Apellidos",
                                           'class':'form-control'}
                                ))
    fechaNac = forms.DateField(label="Fecha de Nacimiento(opcional)",
                                   widget=forms.DateInput(
                                       attrs={'placeholder':"mm/dd/aaaa",
                                                'class':'form-control'}
                                )) 
    email = forms.EmailField(label="Correo electrónico*",
                             required=True,
                            validators=[
                                #por defecto el campo emailfiel saca un mensaje de error entre a valida email adress
                                #validators.EmailValidator("Introduce un Correo electrónico correcto", "Invalid E-mail"),
                                    ],     
                             widget=forms.EmailInput(
                                 attrs={"placeholder":"Correo electrónico",
                                        'class':'form-control'}
                             ))
    password1 = forms.CharField(label="Contraseña*",
                                required=True,
                                validators=[
                                    validators.MinLengthValidator(8,"Tu contraseña debe tener al menos 8 caracteres")
                                    ],
                                widget=forms.PasswordInput(
                                    attrs={'placeholder':"Contraseña",
                                            'class':'form-control'}))  
    password2 = forms.CharField(label="Repite Contraseña*",
                                required=True,
                                validators=[
                                    validators.MinLengthValidator(8,"Tu contraseña debe tener al menos 8 caracteres")
                                    ],
                                widget=forms.PasswordInput(
                                    attrs={'placeholder':"Contraseña",
                                            'class':'form-control'})) 



class LoginForm(forms.Form):
    email = forms.EmailField(label="Correo electrónico",
                             required=True,
                             widget=forms.EmailInput(
                                 attrs={'placeholder':"Correo electrónico",
                                        'class':'form-control'}))
    password = forms.CharField(label="Contraseña",
                               required=True,
                                widget=forms.PasswordInput(
                                    attrs={'placeholder':"Contraseña",
                                            'class':'form-control'}))

    
    def clean_email(self):
        # esto que se recoje es un e-mail
        email = self.cleaned_data.get('email')
        try:
            user = User.objects.get(email=email)
            print(user.email)
        except User.DoesNotExist:
            raise forms.ValidationError("Estas seguro que estas registrado? Usuario no encontrado.")
        return email
    

    def clean_password(self):
        # esto que se recoje es un e-mail
        email = self.cleaned_data.get('email')  
        password = self.cleaned_data.get('password')
        try:
            user = User.objects.get(email=email)
            print(user.email)   
        except:
            user = None
        # si el usuario existe y la password es incorrecta
        if user is not None and not user.check_password(password):
            raise forms.ValidationError("Contraseña Inválida.")
        elif user is None:
            pass
        #este else es, que el usuario existe y la password es correcta
        else:
            print("pasa por el else de return password")
            return password
        print("pasa por la funcion principal")
        return password
   

cuenta/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout, login, authenticate

from cuenta.models import UsuarioStripe
from cuenta.forms import RegistrationForm
from cuenta.forms import LoginForm


def logout_view(request):
    logout(request)
    return redirect("all_products")


def register_partial_view(request):
    return render(request, "cuentas/partials/register_partial.html")


def login_partial_view(request):
    form = LoginForm(request.POST or None)

    if form.is_valid():
        email = form.cleaned_data['email']
        password = form.cleaned_data['password']
        user = authenticate(username=email, password= password)
        print(user)
        login(request, user)
        #return redirect("all_products")    
    return render(request, "cuentas/partials/login_partial.html", {"form":form})


def register_view(request):
    form= RegistrationForm(request.POST or None)
    if form.is_valid():
        fecha = form.cleaned_data.get('fechaNac')
        #password1 = form.cleaned_data.get('password1')
        new_user = form.save()
        
        new_user_stripe = UsuarioStripe.objects.create(
            usuario= new_user,
            fecha_nacimiento = fecha
        )

        #new_user.set_password(password1)
    
        #return redirect("cuentas:auth_login")
    return render(request, "cuentas/register.html",{"form":form})


def login_view(request):
    form = LoginForm(request.POST or None)

    if form.is_valid():
        email = form.cleaned_data['email']
        password = form.cleaned_data['password']
        user = authenticate(username=email, password= password)
        print(user)
        login(request, user)
        #return redirect("all_products")


    return render(request,"cuentas/login.html", {"form":form})

templates/cuentas/partials/login_partial.html
    <h1>Te damos la bienvenida</h1>
    <form action="{% url 'cuentas:auth_login'%}" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <div class="d-grid gap-2">
            <button class="btn btn-dark" type="submit" class="btn btn-primary">Iniciar sesión</button>
        </div>

    </form>
    <div style="margin-top:10px;">
        <span style="color: blueviolet;">¿Has olvidado tu contraseña?</span>
    </div>

    <hr>


    <h1>Soy nuevo/a</h1>
    <div class="d-grid gap-2">
        <button id="btn-registro" class="btn btn-dark" type="button" class="btn btn-primary">Regístrate</button>
    </div>
    <script>
        $(document).ready(function () {
            $('#btn-registro').click(function () {
                //$('#mostrar-boton-login').toggle('slow');
                //$('#mostrar-boton-registro').toggle('slow');
            
                $("#mostrar").load("{% url 'cuentas:auth_register_partial' %}");
            });
        });
    </script>

 

templates/cuentas/partials/register_partial.html
 
        <h1>Te damos la bienvenida</h1>
        <div class="d-grid gap-2">
            <button id="btn-login" class="btn btn-dark" type="button">Iniciar sesión</button>
        </div>
        <hr>

        <h1>Soy nuevo/a</h1>
        <form>
            <p>Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el
                texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se
                dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un
                libro de textos especimen. No sólo sobrevivió 500 años, sino que tambien ingresó como texto de relleno en
                documentos electrónicos, quedando esencialmente igual al original. Fue popularizado en los 60s con la
                creación de las hojas "Letraset", las cuales contenian pasajes de Lorem Ipsum, y más recientemente con
                software de autoedición, como por ejemplo Aldus PageMaker, el cual incluye versiones de Lorem Ipsum.</p>
        
            <div class="d-grid gap-2">
                <button class="btn btn-dark">Regístrate</button>
            </div>
        </form>
        <script>
            $(document).ready(function () {
                $('#btn-login').click(function () {
                    //$('#mostrar-boton-login').toggle('slow');
                    //$('#mostrar-boton-registro').toggle('slow');
                
                    $("#mostrar").load("{% url 'cuentas:auth_login_partial' %}");
                });
            });
        </script>